server:
  port: 9002
spring:
  application:
    name: gateway9002
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #启用DiscoveryClient网关集成，可以实现服务的发现
      routes:
        #自定义谓词UserNameCheckRoutePredicateFactory的配置使用
        #谓词用来匹配路径
        - id: gateway-weight-high
          uri: http://jd.com
          predicates:
            - Path=/weight
            - Weight= Group1, 1
        - id: gateway-weight-low
          uri: http://baidu.com
          predicates:
            - Path=/weight
            - Weight= Group1, 1
        - id: Auth_route
          #uri: lb://nacos-provider7001 #目标URL，lb代表从注册中心获取服务
          #uri: http://localhost:7001
          uri: http://localhost:7001/provider
          predicates:
            - Path=/provider
#            - Token=123456    #自定义谓词
#            - TimeBetween=上午11:00, 下午12:00  #自定义谓词
#            - Query=p1
#            - RemoteAddr=192.168.1.1/32
#            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
#            - Between=2018-01-20T06:06:06+08:00[Asia/Shanghai], 2022-01-20T06:06:06+08:00[Asia/Shanghai]
#            - Before=2022-01-20T06:06:06+08:00[Asia/Shanghai]
#            - Cookie=token, 123456
#            - Header=X-Request-Id, \d+
#            - Host=**.lph.com
#            - Method=GET
          filters:
              - AddRequestHeader=x-token,xxxxx
              - RequestLog=prefix, gateway #自定义过滤器
    #服务注册发现的nacos
    nacos:
      discovery:
        server-addr: localhost:8848


